drive_joint_name: wheels
steering_joint_name: steering_angle

steering_servo_arm_joint_name: steering_servo_arm_joint

front_left_wheel_joint_name: front_left_wheel_joint
front_right_wheel_joint_name: front_right_wheel_joint
rear_left_wheel_joint_name: rear_left_wheel_joint
rear_right_wheel_joint_name: rear_right_wheel_joint
front_left_steering_joint_name: front_left_steering_joint
front_right_steering_joint_name: front_right_steering_joint

servo_id: 1

scservo_driver:
  servos: [1]

  servo_1:
    max_torque: 568
    max_angle_limit: 712
    min_angle_limit: 277
    rad_offset: -1.7766
    rad_per_tick: -0.003695991
