scservo_driver:
  servos: [1]

  servo_1:
    max_torque: 400
    max_angle_limit: 712
    min_angle_limit: 277
    rad_offset: -1.7766
    rad_per_tick: -0.003695991

    actuator_name: steering_servo

vesc_driver:
  actuator_name: drive_motor
